name: Laravel Tests # Este es el nombre del job principal

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: aluvid_pi
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Cambia a la versión de PHP que estés utilizando
        extensions: mbstring, pdo, pdo_mysql
        ini-values: |
          memory_limit=-1
        coverage: none

    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Set up .env
      run: cp .env.example .env

    - name: Configure .env database variables
      run: |
        php artisan key:generate
        sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=mysql/' .env
        sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env
        sed -i 's/DB_PORT=3306/DB_PORT=3306/' .env
        sed -i 's/DB_DATABASE=laravel/DB_DATABASE=aluvid_pi/' .env
        sed -i 's/DB_USERNAME=root/DB_USERNAME=root/' .env
        sed -i 's/DB_PASSWORD=/DB_PASSWORD=root/' .env

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test

    - name: Create ZIP of project
      run: zip -r my_laravel_project.zip . -x "vendor/*" "node_modules/*"

    - name: Almacenamiento de artefactos
      uses: actions/upload-artifact@v3
      with:
        name: my-laravel-artifact
        path: my_laravel_project.zip
    
    - name: Despliegue automatizado
      run: |
        docker-compose down || true # Detiene contenedores anteriores si existen
        docker-compose up -d --build
      env:
        APP_ENV: production
        APP_KEY: ${{ secrets.APP_KEY }}
        DB_CONNECTION: mysql
        DB_HOST: localhost
        DB_PORT: 3306
        DB_DATABASE: aluvid_pi
        DB_USERNAME: root
        DB_PASSWORD: root

