name: Laravel Tests2

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: aluvid_pi
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, pdo_mysql
        ini-values: |
          memory_limit=-1
        coverage: none

    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Set up .env
      run: cp .env.example .env

    - name: Configure .env database variables
      run: |
        php artisan key:generate
        sed -i 's/DB_DATABASE=laravel/DB_DATABASE=${{ secrets.DB_DATABASE }}/' .env
        sed -i 's/DB_USERNAME=root/DB_USERNAME=${{ secrets.DB_USERNAME }}/' .env
        sed -i 's/DB_PASSWORD=/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/' .env

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test

    - name: Build Docker image
      run: docker build -t my-app .

    - name: Run Docker container
      run: docker run -d -p 8080:8080 --name my-app-container my-app

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    - name: Save 

